### ISSUE TITLE
Can't specify RegistrationForm (form_class) to be used by the default backend

### ISSUE THREAD

**Issue by atleta** [macropin/django-registration#27]
It seems that there is no way to set the form_class for backends.default.RegsitrationView . The documentation says something about providing a keyword argument to 'registration()' (sic), but it seems to have been left there from an earlier version. At least I can't interpret it.

Also, I have looked through the code and can't see any sign of using anything but using the wired in form_class (specified in registration.views.RegistrationView). I would make it a setting in settings. If you are OK with it, I can create a pull request.

(Note, that I'm trying to upgrade from 0.8.0 where this could be handled through providing my own backend class.)

**Comment by macropin** [comment]
I suspect we need the docs updated here. I'll mark this as a bug

**Comment by wfranzini** [comment]
I've the same problem, but it seems that feature (REGISTRATION_FORM) is not available in v1.1.
Maybe the documentation refers to the development version.

**Comment by martey** [comment]
I think I ran into the same problem while upgrading from django-registration. I had previously subclassed RegistrationView with a custom `form_class`; django-registration-redux did not work until I added a `REGISTRATION_FORM` setting.

This took more time than I would have liked to fix, because the documentation (immediately below the information about `REGISTRATION_FORM`) claims that overriding `form_class` works and that there are no backwards incompatible changes when upgrading from django-registration.

**Comment by macropin** [comment]
I believe this is resolved by the release 1.2, about to go out.

**Comment by martey** [comment]
I tried 1.2c0, but this isn't resolved.

Before 4d9c72e000a1a0a22b04f7b6f12b79634eadbeb1, you could use a custom registration form by subclassing RegistrationView and using a custom form_class. After that commit, you must use `REGISTRATION_FORM`.

I don't see using a setting as superior to subclassing (especially since this breaks backwards compatibility with the original django-registration), but maybe @laginha can explain.

**Comment by laginha** [comment]
Subclassing `RegistrationView` and overriding `form_class` should work. Can you provide details of the error?

**Comment by martey** [comment]
If I am using a custom user Model (`EmailUser`) that does not have the username field and do not set the `REGISTRATION_FORM` setting, I get the following error:
````python
FieldError: Unknown field(s) (username) specified for EmailUser

  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/registration/views.py", line 22, in <module>
    REGISTRATION_FORM = import_string( REGISTRATION_FORM_PATH )
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/registration/forms.py", line 20, in <module>
    class RegistrationForm(UserCreationForm):
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/forms/models.py", line 295, in __new__
    raise FieldError(message)

````

**Comment by AMeng** [comment]
@martey I'm not able to reproduce this. When do you see this error? Is that a full traceback you posted?

The commit you referred to (https://github.com/macropin/django-registration/commit/4d9c72e000a1a0a22b04f7b6f12b79634eadbeb1) only changes where the default is pulled form. Overriding it still works for me.

It might help if you post your custom form, custom model, and custom view if you have one.

**Comment by laginha** [comment]
Since you are using a custom user model (with no username field) and Django does some actual work without you even initialising the `RegistrationForm`, the error is raised.

I've made a [pull request](https://github.com/macropin/django-registration/pull/58) with a fix.

**Comment by martey** [comment]
> The commit you referred to (4d9c72e) only changes where the default is pulled form. Overriding it still works for me.

Because of that commit, If you don't set `REGISTRATION_FORM`,  the code  will still import `registration.forms.RegistrationForm`. Since my custom user model does not have a field called "username", it raises a FieldError during this import.

@laginha, your changes fixed the FieldError.

I still think that the `REGISTRATION_FORM` setting is not necessary and should be removed, since it duplicates the same behavior as subclassing RegistrationView and overriding `form_class` (which the documentation suggests is the best way to change the registration form or other behavior).
