### ISSUE TITLE
Import of deprecated object RequestSite (removed in django 1.9)

### ISSUE THREAD

**Issue by dwt** [macropin/django-registration#66]
The problem is that in https://github.com/macropin/django-registration/blob/master/registration/admin.py#L2 RequestSite is imported as ``from django.contrib.sites.models import RequestSite`` - but it has moved to ``django.contrib.sites.requests``

Please fix, as the plugin is unusable with django 1.9 otherwise.

**Comment by macropin** [comment]
Should be solved by #69

**Comment by sefakilic** [comment]
Is this change included in version 1.2? I am using django-registration installed via pip and still getting RequestSite import error.

**Comment by macropin** [comment]
Don't think so. Please try from git. We probably should push out 1.3 soon...

**Comment by sefakilic** [comment]
Manual installation from git works just fine. Thanks!
